# Generated by Django 5.0.6 on 2024-06-06 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_delete_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the incident')),
                ('location', models.CharField(max_length=100, verbose_name='Location of the incident')),
                ('description', models.TextField(verbose_name='Incident Description')),
                ('victim_injury', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is the Individual Injured')),
                ('witness_present', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is there a Witness Present')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
            ],
        ),
    ]
